# sample docker-compose deployment file
version: "2"
services:
  njs-dns-proxy:
    image: "marlic/rpi-njs-dns-proxy:1.0.3"
    container_name: njs_dns_proxy
    ports:
      - 53:8053
    volumes:
      - ./conf.json:/home/node/conf.json
    restart: always
  # environment:
  #   - DEBUG=dnsproxy:debug,dnsproxy:query,dnsproxy:info
